### ISSUE TITLE
Fill in the pawns

### ISSUE THREAD

**Issue by rpdelaney** [trevorbayless/cli-chess#17]
### What feature would you like to see in cli-chess?

Black and white pawns look too similar.

**Comment by trevorbayless** [comment]
Thank you for the enhancement request. This actually was a deliberate choice during development as the unicode symbol for a white pawn `\u265F` in many fonts is actually rendered as the pawn emoji. Even if I exposed the chess pieces for customization to the user, I think we'd be in the same situation.

![image](https://user-images.githubusercontent.com/3620552/229298927-8ad9ad3c-8cd7-4c8e-ba8a-0189ae704e70.png)

![image](https://user-images.githubusercontent.com/3620552/229299244-0612a7ee-e0b2-4ba1-a8ab-8946a9cbe47c.png)

**Comment by rpdelaney** [comment]
Okay, so this is really a feature request for my font, not cli-chess. That's fair. Thanks!
