### ISSUE TITLE
Offline game rated 1500 played like 500

### ISSUE THREAD

**Issue by R-Rothrock** [trevorbayless/cli-chess#20]
### Steps to reproduce the bug

Play offline game against fairy stockfish (elo 1500 in my game.)

Didn’t take back on exchanges, gave up pieces, etc. Nothing near a level 1500 bot. 

### Operating system

Kali Linux 

### Terminal and version

Zsh 5.9 but I doubt it matters

### cli-chess version

1.0.0

**Comment by trevorbayless** [comment]
Thank you for reporting. I've confirmed on my end that the strength is being set correctly and passed along to the engine:

![image](https://user-images.githubusercontent.com/3620552/231592807-1f152958-ea76-4dbb-808a-592b6e1e468c.png)

You can check on your end if this is being set correctly by opening the `chess.engine.log` located at `$HOME/.config/cli-chess/` and starting a game against the engine. Please let me know if you see this value being set differently.

While investigating this, I've played multiple games with the ELO set to 1500 and have seen it not take back, but haven't seen play anywhere near a 500 as you mentioned. Have you seen this issue with the ELO set higher as well?

There are multiple factors that go into how the `UCI_Elo` was calibrated on the Stockfish / Fairy-Stockfish side. One of them being a set time control of [60s+0.6s](https://github.com/fairy-stockfish/Fairy-Stockfish/#uci_elo). 

cli-chess currently does not have clocks on offline games (there's an open enhancement for it [here](https://github.com/trevorbayless/cli-chess/issues/10). Once the clock has been implemented, the time data will be passed along to the engine for it to respond accordingly.

**Comment by R-Rothrock** [comment]
I played another game, and I see what you're talking about:

> setoption name UCI_Elo value 1500

Didn't look like it though. Maybe my computers just garbage \:

Anyway. Seems like it's likely not on your end. Maybe level 1500 fairy SF doesn't understand the Slav defense.
