### ISSUE TITLE
Add blitz time control

### ISSUE THREAD

**Issue by MeiH10** [trevorbayless/cli-chess#21]
### What feature would you like to see in cli-chess?

Add blitz(5 min) time control

**Comment by trevorbayless** [comment]
Blitz time control (3-5min) is available and implemented in _Online games against the computer_. Unfortunately, the same cannot be implemented on games vs random opponents as it is restricted by Lichess. Here's the explanation Lichess provided in one of their API blogs:

> **Why is it restricted to Rapid, Classical and Correspondence?**
For cheating reasons. When moves are received through an API, Lichess can't tell who really played them. Is could be a person, or a chess engine. The Lichess website and mobile app embed cheat detection tools that help us know if moves are played fairly. But APIs bypass these tools.
Of course, most of our cheat detection happens on the server-side, and therefore also applies to the Board API. But we still don't feel comfortable giving up on client-side detection for any games faster than Rapid.
**_Source:_** https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards
