### ISSUE TITLE
cant run on google colab

### ISSUE THREAD

**Issue by sugizo** [trevorbayless/cli-chess#23]
### Steps to reproduce the bug

steps to reproduce
```
pip install -U cli-chess
!cli-chess 
```

![image](https://github.com/trevorbayless/cli-chess/assets/2418295/bfc8eba6-cef3-4801-bea0-09ef45b68437)

### Operating system

ubuntu on google colab

### Terminal and version

ubuntu on google colab

### cli-chess version

1.0.1

### Additional information

when use [ARROWS] to navigate the menus. 
it will change the browser scrollbar up, down

When Use [SPACEBAR] or [ENTER] to modify values.
it will type the space horizontal (spacebar) 
or 
vertical space / carriage return (enter)

![image](https://github.com/trevorbayless/cli-chess/assets/2418295/bfc8eba6-cef3-4801-bea0-09ef45b68437)

**Comment by trevorbayless** [comment]
Thanks for reporting. Unfortunately I don't have a subscription to Colab Pro to look further into this. My first thought would be that the application is not receiving the proper focus. I also see that you are missing the bottom toolbar which should show the "Start game" and "Quit" options.

How does google colab render other TUI applications? For example, if you install and run `htop` are you able to navigate the process list using the keyboard?

**Comment by trevorbayless** [comment]
Closing as not planned currently. Without a subscription to Colab Pro this issue can not be investigated.
