### ISSUE TITLE
“Error starting engine: engine process died unexpectedly (exit code: 1)”

### ISSUE THREAD

**Issue by FauveNoir** [trevorbayless/cli-chess#25]
### Steps to reproduce the bug

1. run `cli-chess`
2. press <kbd>F1</kbd>

Then I get a message warning me that fairy-stockfish died

<img src="https://i.imgur.com/yyiPSnG.png" />

I tryed `fairychess` with other interfaces and it work.

### Operating system

5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

### Terminal and version

Urxvt, Kitty, gnome-terminal

### cli-chess version

cli-chess v1.1.0

### Additional information

Fairy-Stockfish 11.1 LB 64 by Fabian Fichter

**Comment by trevorbayless** [comment]
Are you using the PyPI release or building from source and attempting to use a different engine binary? You mentioned in the additional information `Fairy-Stockfish 11.1` but what comes bundled with cli-chess is `Fairy-Stockfish 14`.

**Comment by trevorbayless** [comment]
Following up on the previous question. If this issue is with the cli-chess provided fairy-stockfish binaries please attach the engine logs (they can be found at `~/.config/cli-chess/chess.engine.log`).

**Comment by trevorbayless** [comment]
Closing as there is a lack of additional information. If the problem persists when using the cli-chess provided Fairy-Stockfish binary, please open a new issue providing the engine logs.
