### ISSUE TITLE
Vi-like menus

### ISSUE THREAD

**Issue by Muxutruk2** [trevorbayless/cli-chess#28]
### What feature would you like to see in cli-chess?

I would like an option to be able to navigate the menus with vim-like movements, for example: main menu would be:
:offline
:online
(these last 2 maybe available whenever)
:settings
:about
Then, after choosing one you could go back with :q 
The match configuration panel is good, no need to change it
And when in a match you could
:e4 or.. :move e4
:flip
:takeback
:draw
:resign

What do you think?

**Comment by Muxutruk2** [comment]
Well, making it optional and default to off, i dont see any problems

**Comment by trevorbayless** [comment]
Closing as not planned for now due to added complexity.
