### ISSUE TITLE
Added option to enlarge game board

### ISSUE THREAD

**Issue by KevinGIRAULT** [trevorbayless/cli-chess#30]
### What feature would you like to see in cli-chess?

Hello,

I've just discovered cli-chess. It's cool, however, I've noticed that the game board is quite small, which can make viewing and selecting pieces a little difficult. I know that most terminals allow you to zoom in, but : 

- not all of them do (e.g. the `st` terminal in its default version).
- it's more convenient to have the choice between the game and the terminal.
- the tty console doesn't allow zooming (tmux would probably make up for this, but it adds another tool for those who don't want it).

So allowing zooming (and saving the chosen option for next times) would be cool. I don't have a preference on how to do it. 

Thanks for reading...

**Comment by trevorbayless** [comment]
Hello,

I wish I could provide better news, but unfortunately there isn't a way for cli-chess to programmatically manage this. cli-chess is reliant on the user zooming or changing the font size to their preference. Some terminals allow setting up a "profile", so you could set one specific to cli-chess if you desire as well.

Regarding `st`, you should be able to zoom using `Ctrl + Shift + PgUp/PgDn`.

**Comment by KevinGIRAULT** [comment]
Okay thank you.
